/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { ApprovalTarget__factory } from "./ApprovalTarget__factory";
export { GovernableApprovalTarget__factory } from "./GovernableApprovalTarget__factory";
