/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as veTahoSol from "./VeTaho.sol";
export { GameParameters__factory } from "./GameParameters__factory";
export { Node__factory } from "./Node__factory";
