/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IHuntingGroundRegistry,
  IHuntingGroundRegistryInterface,
} from "../../../../contracts/hunting-grounds/interfaces/IHuntingGroundRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "ground",
        type: "address",
      },
    ],
    name: "registerHuntingGround",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHuntingGroundRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IHuntingGroundRegistryInterface {
    return new utils.Interface(_abi) as IHuntingGroundRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHuntingGroundRegistry {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IHuntingGroundRegistry;
  }
}
