/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IYearnRegistryV2,
  IYearnRegistryV2Interface,
} from "../../../../contracts/hunting-grounds/interfaces/IYearnRegistryV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "governance",
        type: "address",
      },
      {
        internalType: "address",
        name: "guardian",
        type: "address",
      },
      {
        internalType: "address payable",
        name: "rewards",
        type: "address",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
    ],
    name: "newExperimentalVault",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IYearnRegistryV2__factory {
  static readonly abi = _abi;
  static createInterface(): IYearnRegistryV2Interface {
    return new utils.Interface(_abi) as IYearnRegistryV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IYearnRegistryV2 {
    return new Contract(address, _abi, signerOrProvider) as IYearnRegistryV2;
  }
}
