[build]
# environment = { NODE_VERSION = "18.16.1" }
  base = "/"
  command = "yarn build"
  functions = "functions"
  publish = "./dist/"

[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"