/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface ApprovalTargetInterface extends utils.Interface {
  functions: {
    "DOMAIN_SEPARATOR()": FunctionFragment;
    "PERMIT_AND_TRANSFER_FROM_TYPEHASH()": FunctionFragment;
    "cachedChainId()": FunctionFragment;
    "cachedDomainSeparator()": FunctionFragment;
    "nonces(address)": FunctionFragment;
    "permitAndTransferFrom(address,address,address,uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "recoverFromTypeHashSignature(bytes32,uint8,bytes32,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DOMAIN_SEPARATOR"
      | "PERMIT_AND_TRANSFER_FROM_TYPEHASH"
      | "cachedChainId"
      | "cachedDomainSeparator"
      | "nonces"
      | "permitAndTransferFrom"
      | "recoverFromTypeHashSignature"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERMIT_AND_TRANSFER_FROM_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cachedChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cachedDomainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [string]): string;
  encodeFunctionData(
    functionFragment: "permitAndTransferFrom",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverFromTypeHashSignature",
    values: [BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERMIT_AND_TRANSFER_FROM_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cachedChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cachedDomainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "permitAndTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverFromTypeHashSignature",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ApprovalTarget extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ApprovalTargetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<[string]>;

    PERMIT_AND_TRANSFER_FROM_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    cachedChainId(overrides?: CallOverrides): Promise<[BigNumber]>;

    cachedDomainSeparator(overrides?: CallOverrides): Promise<[string]>;

    nonces(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    permitAndTransferFrom(
      erc20: string,
      owner: string,
      recipient: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    recoverFromTypeHashSignature(
      typeHashDigest: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

  PERMIT_AND_TRANSFER_FROM_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  cachedChainId(overrides?: CallOverrides): Promise<BigNumber>;

  cachedDomainSeparator(overrides?: CallOverrides): Promise<string>;

  nonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  permitAndTransferFrom(
    erc20: string,
    owner: string,
    recipient: string,
    amount: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  recoverFromTypeHashSignature(
    typeHashDigest: BytesLike,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

    PERMIT_AND_TRANSFER_FROM_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<string>;

    cachedChainId(overrides?: CallOverrides): Promise<BigNumber>;

    cachedDomainSeparator(overrides?: CallOverrides): Promise<string>;

    nonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    permitAndTransferFrom(
      erc20: string,
      owner: string,
      recipient: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    recoverFromTypeHashSignature(
      typeHashDigest: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<BigNumber>;

    PERMIT_AND_TRANSFER_FROM_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cachedChainId(overrides?: CallOverrides): Promise<BigNumber>;

    cachedDomainSeparator(overrides?: CallOverrides): Promise<BigNumber>;

    nonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    permitAndTransferFrom(
      erc20: string,
      owner: string,
      recipient: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    recoverFromTypeHashSignature(
      typeHashDigest: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PERMIT_AND_TRANSFER_FROM_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cachedChainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cachedDomainSeparator(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nonces(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    permitAndTransferFrom(
      erc20: string,
      owner: string,
      recipient: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    recoverFromTypeHashSignature(
      typeHashDigest: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
