/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ApprovalTarget } from "./ApprovalTarget";
export type { GovernableApprovalTarget } from "./GovernableApprovalTarget";
