/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EducateNode } from "./EducateNode";
export type { EducateNodeDeployer } from "./EducateNodeDeployer";
