/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TokenWithCompoundStyleDelegation,
  TokenWithCompoundStyleDelegationInterface,
} from "../../../../contracts/distributors/VoteWithFriends.sol/TokenWithCompoundStyleDelegation";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "delegatee",
        type: "address",
      },
    ],
    name: "delegate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "delegatee",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "delegateBySig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class TokenWithCompoundStyleDelegation__factory {
  static readonly abi = _abi;
  static createInterface(): TokenWithCompoundStyleDelegationInterface {
    return new utils.Interface(
      _abi
    ) as TokenWithCompoundStyleDelegationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenWithCompoundStyleDelegation {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TokenWithCompoundStyleDelegation;
  }
}
