export const LOCAL_STORAGE_ASSISTANT = "taho.assistant"
export const LOCAL_STORAGE_WALLET = "onboarded_wallet"
export const LOCAL_STORAGE_VISITED_REALM = "taho.visitedRealm"
export const LOCAL_STORAGE_BRAVE = "taho.brave"
export const LOCAL_STORAGE_COOKIES = "taho.cookies"
export const LOCAL_STORAGE_DISPLAYED_REALMS = "taho.displayedRealm"
export const LOCAL_STORAGE_DISPLAYED_CHALLENGES = "taho.displayedChallenges"
export const LOCAL_STORAGE_CACHED_NAMES = "taho.cachedNames"
