/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface TahoDeployerInterface extends utils.Interface {
  functions: {
    "APPROVAL_TARGET()": FunctionFragment;
    "APPROVAL_TARGET_DEPLOY_HASH()": FunctionFragment;
    "BALANCER_DEPLOYER_DEPLOY_HASH()": FunctionFragment;
    "BALANCER_POOL()": FunctionFragment;
    "BALANCER_POOL_CANDIDATE()": FunctionFragment;
    "CREATORS_NODE()": FunctionFragment;
    "CREATORS_NODE_DEPLOYER_DEPLOY_HASH()": FunctionFragment;
    "CREATORS_NODE_VETAHO()": FunctionFragment;
    "CREATORS_NODE_VETAHO_DEPLOY_HASH()": FunctionFragment;
    "DEFI_NODE()": FunctionFragment;
    "DEFI_NODE_DEPLOYER_DEPLOY_HASH()": FunctionFragment;
    "DEFI_NODE_VETAHO()": FunctionFragment;
    "DEFI_NODE_VETAHO_DEPLOY_HASH()": FunctionFragment;
    "EDUCATE_NODE()": FunctionFragment;
    "EDUCATE_NODE_DEPLOYER_DEPLOY_HASH()": FunctionFragment;
    "EDUCATE_NODE_VETAHO()": FunctionFragment;
    "EDUCATE_NODE_VETAHO_DEPLOY_HASH()": FunctionFragment;
    "EXPIRING_MERKLE_DISTRIBUTOR_FACTORY()": FunctionFragment;
    "GAME_PARAMETERS()": FunctionFragment;
    "GAME_PARAMETERS_DEPLOY_HASH()": FunctionFragment;
    "GOVERNOR_BRAVO_V1_BASE_DELEGATE()": FunctionFragment;
    "HUNTING_GROUND_REGISTRY()": FunctionFragment;
    "HUNTING_GROUND_REGISTRY_DEPLOY_HASH()": FunctionFragment;
    "MERKLE_FACTORY_DEPLOYER_DEPLOY_HASH()": FunctionFragment;
    "SOCIAL_NODE()": FunctionFragment;
    "SOCIAL_NODE_DEPLOYER_DEPLOY_HASH()": FunctionFragment;
    "SOCIAL_NODE_VETAHO()": FunctionFragment;
    "SOCIAL_NODE_VETAHO_DEPLOY_HASH()": FunctionFragment;
    "TAHOETH_HUNTING_GROUND_DEPLOYER_DEPLOY_HASH()": FunctionFragment;
    "TAHO_COMMUNITY_MULTISIG()": FunctionFragment;
    "TAHO_DEPLOY_HASH()": FunctionFragment;
    "TAHO_GOVERNOR_BRAVO_DELEGATE_DEPLOY_HASH()": FunctionFragment;
    "TAHO_GOVERNOR_BRAVO_DELEGATOR_DEPLOY_HASH()": FunctionFragment;
    "TAHO_SALT()": FunctionFragment;
    "TAHO_TOKEN()": FunctionFragment;
    "TIMELOCK()": FunctionFragment;
    "TIMELOCK_DEPLOYER_DEPLOY_HASH()": FunctionFragment;
    "TREASURY_VESTER()": FunctionFragment;
    "TREASURY_VESTER_DEPLOYER_DEPLOY_HASH()": FunctionFragment;
    "VAMPIRE_NODE()": FunctionFragment;
    "VAMPIRE_NODE_DEPLOYER_DEPLOY_HASH()": FunctionFragment;
    "VAMPIRE_NODE_VETAHO()": FunctionFragment;
    "VAMPIRE_NODE_VETAHO_DEPLOY_HASH()": FunctionFragment;
    "VOTE_WITH_FRIENDS()": FunctionFragment;
    "VOTE_WITH_FRIENDS_DEPLOYER_DEPLOY_HASH()": FunctionFragment;
    "arbitraryFinalizationAllowedAfter()": FunctionFragment;
    "contractRewards(bytes32)": FunctionFragment;
    "deploy(bytes)": FunctionFragment;
    "enableTAHOETH()": FunctionFragment;
    "finalize()": FunctionFragment;
    "setBalancerPoolCandidate(address)": FunctionFragment;
    "tahoEthDeployAllowed()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "APPROVAL_TARGET"
      | "APPROVAL_TARGET_DEPLOY_HASH"
      | "BALANCER_DEPLOYER_DEPLOY_HASH"
      | "BALANCER_POOL"
      | "BALANCER_POOL_CANDIDATE"
      | "CREATORS_NODE"
      | "CREATORS_NODE_DEPLOYER_DEPLOY_HASH"
      | "CREATORS_NODE_VETAHO"
      | "CREATORS_NODE_VETAHO_DEPLOY_HASH"
      | "DEFI_NODE"
      | "DEFI_NODE_DEPLOYER_DEPLOY_HASH"
      | "DEFI_NODE_VETAHO"
      | "DEFI_NODE_VETAHO_DEPLOY_HASH"
      | "EDUCATE_NODE"
      | "EDUCATE_NODE_DEPLOYER_DEPLOY_HASH"
      | "EDUCATE_NODE_VETAHO"
      | "EDUCATE_NODE_VETAHO_DEPLOY_HASH"
      | "EXPIRING_MERKLE_DISTRIBUTOR_FACTORY"
      | "GAME_PARAMETERS"
      | "GAME_PARAMETERS_DEPLOY_HASH"
      | "GOVERNOR_BRAVO_V1_BASE_DELEGATE"
      | "HUNTING_GROUND_REGISTRY"
      | "HUNTING_GROUND_REGISTRY_DEPLOY_HASH"
      | "MERKLE_FACTORY_DEPLOYER_DEPLOY_HASH"
      | "SOCIAL_NODE"
      | "SOCIAL_NODE_DEPLOYER_DEPLOY_HASH"
      | "SOCIAL_NODE_VETAHO"
      | "SOCIAL_NODE_VETAHO_DEPLOY_HASH"
      | "TAHOETH_HUNTING_GROUND_DEPLOYER_DEPLOY_HASH"
      | "TAHO_COMMUNITY_MULTISIG"
      | "TAHO_DEPLOY_HASH"
      | "TAHO_GOVERNOR_BRAVO_DELEGATE_DEPLOY_HASH"
      | "TAHO_GOVERNOR_BRAVO_DELEGATOR_DEPLOY_HASH"
      | "TAHO_SALT"
      | "TAHO_TOKEN"
      | "TIMELOCK"
      | "TIMELOCK_DEPLOYER_DEPLOY_HASH"
      | "TREASURY_VESTER"
      | "TREASURY_VESTER_DEPLOYER_DEPLOY_HASH"
      | "VAMPIRE_NODE"
      | "VAMPIRE_NODE_DEPLOYER_DEPLOY_HASH"
      | "VAMPIRE_NODE_VETAHO"
      | "VAMPIRE_NODE_VETAHO_DEPLOY_HASH"
      | "VOTE_WITH_FRIENDS"
      | "VOTE_WITH_FRIENDS_DEPLOYER_DEPLOY_HASH"
      | "arbitraryFinalizationAllowedAfter"
      | "contractRewards"
      | "deploy"
      | "enableTAHOETH"
      | "finalize"
      | "setBalancerPoolCandidate"
      | "tahoEthDeployAllowed"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "APPROVAL_TARGET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "APPROVAL_TARGET_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BALANCER_DEPLOYER_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BALANCER_POOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BALANCER_POOL_CANDIDATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATORS_NODE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATORS_NODE_DEPLOYER_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATORS_NODE_VETAHO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATORS_NODE_VETAHO_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DEFI_NODE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEFI_NODE_DEPLOYER_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFI_NODE_VETAHO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFI_NODE_VETAHO_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EDUCATE_NODE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EDUCATE_NODE_DEPLOYER_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EDUCATE_NODE_VETAHO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EDUCATE_NODE_VETAHO_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXPIRING_MERKLE_DISTRIBUTOR_FACTORY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GAME_PARAMETERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GAME_PARAMETERS_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNOR_BRAVO_V1_BASE_DELEGATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HUNTING_GROUND_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HUNTING_GROUND_REGISTRY_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MERKLE_FACTORY_DEPLOYER_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOCIAL_NODE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOCIAL_NODE_DEPLOYER_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOCIAL_NODE_VETAHO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOCIAL_NODE_VETAHO_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TAHOETH_HUNTING_GROUND_DEPLOYER_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TAHO_COMMUNITY_MULTISIG",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TAHO_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TAHO_GOVERNOR_BRAVO_DELEGATE_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TAHO_GOVERNOR_BRAVO_DELEGATOR_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TAHO_SALT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TAHO_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIMELOCK", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_DEPLOYER_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_VESTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_VESTER_DEPLOYER_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAMPIRE_NODE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAMPIRE_NODE_DEPLOYER_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAMPIRE_NODE_VETAHO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAMPIRE_NODE_VETAHO_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTE_WITH_FRIENDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTE_WITH_FRIENDS_DEPLOYER_DEPLOY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "arbitraryFinalizationAllowedAfter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contractRewards",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "deploy", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "enableTAHOETH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "finalize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setBalancerPoolCandidate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "tahoEthDeployAllowed",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "APPROVAL_TARGET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "APPROVAL_TARGET_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BALANCER_DEPLOYER_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BALANCER_POOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BALANCER_POOL_CANDIDATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CREATORS_NODE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CREATORS_NODE_DEPLOYER_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CREATORS_NODE_VETAHO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CREATORS_NODE_VETAHO_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DEFI_NODE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFI_NODE_DEPLOYER_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFI_NODE_VETAHO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFI_NODE_VETAHO_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EDUCATE_NODE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EDUCATE_NODE_DEPLOYER_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EDUCATE_NODE_VETAHO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EDUCATE_NODE_VETAHO_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXPIRING_MERKLE_DISTRIBUTOR_FACTORY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GAME_PARAMETERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GAME_PARAMETERS_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNOR_BRAVO_V1_BASE_DELEGATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HUNTING_GROUND_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HUNTING_GROUND_REGISTRY_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MERKLE_FACTORY_DEPLOYER_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOCIAL_NODE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOCIAL_NODE_DEPLOYER_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOCIAL_NODE_VETAHO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOCIAL_NODE_VETAHO_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TAHOETH_HUNTING_GROUND_DEPLOYER_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TAHO_COMMUNITY_MULTISIG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TAHO_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TAHO_GOVERNOR_BRAVO_DELEGATE_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TAHO_GOVERNOR_BRAVO_DELEGATOR_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TAHO_SALT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TAHO_TOKEN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TIMELOCK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_DEPLOYER_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_VESTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_VESTER_DEPLOYER_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAMPIRE_NODE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAMPIRE_NODE_DEPLOYER_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAMPIRE_NODE_VETAHO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAMPIRE_NODE_VETAHO_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTE_WITH_FRIENDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTE_WITH_FRIENDS_DEPLOYER_DEPLOY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "arbitraryFinalizationAllowedAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enableTAHOETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "finalize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBalancerPoolCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tahoEthDeployAllowed",
    data: BytesLike
  ): Result;

  events: {
    "Deployed(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deployed"): EventFragment;
}

export interface DeployedEventObject {
  contractAddress: string;
  deployerAddress: string;
}
export type DeployedEvent = TypedEvent<[string, string], DeployedEventObject>;

export type DeployedEventFilter = TypedEventFilter<DeployedEvent>;

export interface TahoDeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TahoDeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    APPROVAL_TARGET(overrides?: CallOverrides): Promise<[string]>;

    APPROVAL_TARGET_DEPLOY_HASH(overrides?: CallOverrides): Promise<[string]>;

    BALANCER_DEPLOYER_DEPLOY_HASH(overrides?: CallOverrides): Promise<[string]>;

    BALANCER_POOL(overrides?: CallOverrides): Promise<[string]>;

    BALANCER_POOL_CANDIDATE(overrides?: CallOverrides): Promise<[string]>;

    CREATORS_NODE(overrides?: CallOverrides): Promise<[string]>;

    CREATORS_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    CREATORS_NODE_VETAHO(overrides?: CallOverrides): Promise<[string]>;

    CREATORS_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    DEFI_NODE(overrides?: CallOverrides): Promise<[string]>;

    DEFI_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    DEFI_NODE_VETAHO(overrides?: CallOverrides): Promise<[string]>;

    DEFI_NODE_VETAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<[string]>;

    EDUCATE_NODE(overrides?: CallOverrides): Promise<[string]>;

    EDUCATE_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    EDUCATE_NODE_VETAHO(overrides?: CallOverrides): Promise<[string]>;

    EDUCATE_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    EXPIRING_MERKLE_DISTRIBUTOR_FACTORY(
      overrides?: CallOverrides
    ): Promise<[string]>;

    GAME_PARAMETERS(overrides?: CallOverrides): Promise<[string]>;

    GAME_PARAMETERS_DEPLOY_HASH(overrides?: CallOverrides): Promise<[string]>;

    GOVERNOR_BRAVO_V1_BASE_DELEGATE(
      overrides?: CallOverrides
    ): Promise<[string]>;

    HUNTING_GROUND_REGISTRY(overrides?: CallOverrides): Promise<[string]>;

    HUNTING_GROUND_REGISTRY_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    MERKLE_FACTORY_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    SOCIAL_NODE(overrides?: CallOverrides): Promise<[string]>;

    SOCIAL_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    SOCIAL_NODE_VETAHO(overrides?: CallOverrides): Promise<[string]>;

    SOCIAL_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    TAHOETH_HUNTING_GROUND_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    TAHO_COMMUNITY_MULTISIG(overrides?: CallOverrides): Promise<[string]>;

    TAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<[string]>;

    TAHO_GOVERNOR_BRAVO_DELEGATE_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    TAHO_GOVERNOR_BRAVO_DELEGATOR_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    TAHO_SALT(overrides?: CallOverrides): Promise<[string]>;

    TAHO_TOKEN(overrides?: CallOverrides): Promise<[string]>;

    TIMELOCK(overrides?: CallOverrides): Promise<[string]>;

    TIMELOCK_DEPLOYER_DEPLOY_HASH(overrides?: CallOverrides): Promise<[string]>;

    TREASURY_VESTER(overrides?: CallOverrides): Promise<[string]>;

    TREASURY_VESTER_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAMPIRE_NODE(overrides?: CallOverrides): Promise<[string]>;

    VAMPIRE_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAMPIRE_NODE_VETAHO(overrides?: CallOverrides): Promise<[string]>;

    VAMPIRE_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VOTE_WITH_FRIENDS(overrides?: CallOverrides): Promise<[string]>;

    VOTE_WITH_FRIENDS_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    arbitraryFinalizationAllowedAfter(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    contractRewards(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deploy(
      _initCode: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    enableTAHOETH(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    finalize(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setBalancerPoolCandidate(
      balancerPoolCandidate: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    tahoEthDeployAllowed(overrides?: CallOverrides): Promise<[boolean]>;
  };

  APPROVAL_TARGET(overrides?: CallOverrides): Promise<string>;

  APPROVAL_TARGET_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  BALANCER_DEPLOYER_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  BALANCER_POOL(overrides?: CallOverrides): Promise<string>;

  BALANCER_POOL_CANDIDATE(overrides?: CallOverrides): Promise<string>;

  CREATORS_NODE(overrides?: CallOverrides): Promise<string>;

  CREATORS_NODE_DEPLOYER_DEPLOY_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  CREATORS_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

  CREATORS_NODE_VETAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  DEFI_NODE(overrides?: CallOverrides): Promise<string>;

  DEFI_NODE_DEPLOYER_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  DEFI_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

  DEFI_NODE_VETAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  EDUCATE_NODE(overrides?: CallOverrides): Promise<string>;

  EDUCATE_NODE_DEPLOYER_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  EDUCATE_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

  EDUCATE_NODE_VETAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  EXPIRING_MERKLE_DISTRIBUTOR_FACTORY(
    overrides?: CallOverrides
  ): Promise<string>;

  GAME_PARAMETERS(overrides?: CallOverrides): Promise<string>;

  GAME_PARAMETERS_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  GOVERNOR_BRAVO_V1_BASE_DELEGATE(overrides?: CallOverrides): Promise<string>;

  HUNTING_GROUND_REGISTRY(overrides?: CallOverrides): Promise<string>;

  HUNTING_GROUND_REGISTRY_DEPLOY_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  MERKLE_FACTORY_DEPLOYER_DEPLOY_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  SOCIAL_NODE(overrides?: CallOverrides): Promise<string>;

  SOCIAL_NODE_DEPLOYER_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  SOCIAL_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

  SOCIAL_NODE_VETAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  TAHOETH_HUNTING_GROUND_DEPLOYER_DEPLOY_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  TAHO_COMMUNITY_MULTISIG(overrides?: CallOverrides): Promise<string>;

  TAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  TAHO_GOVERNOR_BRAVO_DELEGATE_DEPLOY_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  TAHO_GOVERNOR_BRAVO_DELEGATOR_DEPLOY_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  TAHO_SALT(overrides?: CallOverrides): Promise<string>;

  TAHO_TOKEN(overrides?: CallOverrides): Promise<string>;

  TIMELOCK(overrides?: CallOverrides): Promise<string>;

  TIMELOCK_DEPLOYER_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  TREASURY_VESTER(overrides?: CallOverrides): Promise<string>;

  TREASURY_VESTER_DEPLOYER_DEPLOY_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  VAMPIRE_NODE(overrides?: CallOverrides): Promise<string>;

  VAMPIRE_NODE_DEPLOYER_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  VAMPIRE_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

  VAMPIRE_NODE_VETAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

  VOTE_WITH_FRIENDS(overrides?: CallOverrides): Promise<string>;

  VOTE_WITH_FRIENDS_DEPLOYER_DEPLOY_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  arbitraryFinalizationAllowedAfter(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  contractRewards(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deploy(
    _initCode: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  enableTAHOETH(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  finalize(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setBalancerPoolCandidate(
    balancerPoolCandidate: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  tahoEthDeployAllowed(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    APPROVAL_TARGET(overrides?: CallOverrides): Promise<string>;

    APPROVAL_TARGET_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

    BALANCER_DEPLOYER_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

    BALANCER_POOL(overrides?: CallOverrides): Promise<string>;

    BALANCER_POOL_CANDIDATE(overrides?: CallOverrides): Promise<string>;

    CREATORS_NODE(overrides?: CallOverrides): Promise<string>;

    CREATORS_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    CREATORS_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

    CREATORS_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    DEFI_NODE(overrides?: CallOverrides): Promise<string>;

    DEFI_NODE_DEPLOYER_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

    DEFI_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

    DEFI_NODE_VETAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

    EDUCATE_NODE(overrides?: CallOverrides): Promise<string>;

    EDUCATE_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    EDUCATE_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

    EDUCATE_NODE_VETAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

    EXPIRING_MERKLE_DISTRIBUTOR_FACTORY(
      overrides?: CallOverrides
    ): Promise<string>;

    GAME_PARAMETERS(overrides?: CallOverrides): Promise<string>;

    GAME_PARAMETERS_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

    GOVERNOR_BRAVO_V1_BASE_DELEGATE(overrides?: CallOverrides): Promise<string>;

    HUNTING_GROUND_REGISTRY(overrides?: CallOverrides): Promise<string>;

    HUNTING_GROUND_REGISTRY_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    MERKLE_FACTORY_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    SOCIAL_NODE(overrides?: CallOverrides): Promise<string>;

    SOCIAL_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    SOCIAL_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

    SOCIAL_NODE_VETAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

    TAHOETH_HUNTING_GROUND_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    TAHO_COMMUNITY_MULTISIG(overrides?: CallOverrides): Promise<string>;

    TAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

    TAHO_GOVERNOR_BRAVO_DELEGATE_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    TAHO_GOVERNOR_BRAVO_DELEGATOR_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    TAHO_SALT(overrides?: CallOverrides): Promise<string>;

    TAHO_TOKEN(overrides?: CallOverrides): Promise<string>;

    TIMELOCK(overrides?: CallOverrides): Promise<string>;

    TIMELOCK_DEPLOYER_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

    TREASURY_VESTER(overrides?: CallOverrides): Promise<string>;

    TREASURY_VESTER_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    VAMPIRE_NODE(overrides?: CallOverrides): Promise<string>;

    VAMPIRE_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    VAMPIRE_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

    VAMPIRE_NODE_VETAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<string>;

    VOTE_WITH_FRIENDS(overrides?: CallOverrides): Promise<string>;

    VOTE_WITH_FRIENDS_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    arbitraryFinalizationAllowedAfter(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractRewards(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deploy(_initCode: BytesLike, overrides?: CallOverrides): Promise<string>;

    enableTAHOETH(overrides?: CallOverrides): Promise<void>;

    finalize(overrides?: CallOverrides): Promise<void>;

    setBalancerPoolCandidate(
      balancerPoolCandidate: string,
      overrides?: CallOverrides
    ): Promise<void>;

    tahoEthDeployAllowed(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "Deployed(address,address)"(
      contractAddress?: string | null,
      deployerAddress?: string | null
    ): DeployedEventFilter;
    Deployed(
      contractAddress?: string | null,
      deployerAddress?: string | null
    ): DeployedEventFilter;
  };

  estimateGas: {
    APPROVAL_TARGET(overrides?: CallOverrides): Promise<BigNumber>;

    APPROVAL_TARGET_DEPLOY_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    BALANCER_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BALANCER_POOL(overrides?: CallOverrides): Promise<BigNumber>;

    BALANCER_POOL_CANDIDATE(overrides?: CallOverrides): Promise<BigNumber>;

    CREATORS_NODE(overrides?: CallOverrides): Promise<BigNumber>;

    CREATORS_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    CREATORS_NODE_VETAHO(overrides?: CallOverrides): Promise<BigNumber>;

    CREATORS_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    DEFI_NODE(overrides?: CallOverrides): Promise<BigNumber>;

    DEFI_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    DEFI_NODE_VETAHO(overrides?: CallOverrides): Promise<BigNumber>;

    DEFI_NODE_VETAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    EDUCATE_NODE(overrides?: CallOverrides): Promise<BigNumber>;

    EDUCATE_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    EDUCATE_NODE_VETAHO(overrides?: CallOverrides): Promise<BigNumber>;

    EDUCATE_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    EXPIRING_MERKLE_DISTRIBUTOR_FACTORY(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GAME_PARAMETERS(overrides?: CallOverrides): Promise<BigNumber>;

    GAME_PARAMETERS_DEPLOY_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    GOVERNOR_BRAVO_V1_BASE_DELEGATE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    HUNTING_GROUND_REGISTRY(overrides?: CallOverrides): Promise<BigNumber>;

    HUNTING_GROUND_REGISTRY_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    MERKLE_FACTORY_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    SOCIAL_NODE(overrides?: CallOverrides): Promise<BigNumber>;

    SOCIAL_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    SOCIAL_NODE_VETAHO(overrides?: CallOverrides): Promise<BigNumber>;

    SOCIAL_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    TAHOETH_HUNTING_GROUND_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    TAHO_COMMUNITY_MULTISIG(overrides?: CallOverrides): Promise<BigNumber>;

    TAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    TAHO_GOVERNOR_BRAVO_DELEGATE_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    TAHO_GOVERNOR_BRAVO_DELEGATOR_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    TAHO_SALT(overrides?: CallOverrides): Promise<BigNumber>;

    TAHO_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

    TIMELOCK(overrides?: CallOverrides): Promise<BigNumber>;

    TIMELOCK_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    TREASURY_VESTER(overrides?: CallOverrides): Promise<BigNumber>;

    TREASURY_VESTER_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAMPIRE_NODE(overrides?: CallOverrides): Promise<BigNumber>;

    VAMPIRE_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAMPIRE_NODE_VETAHO(overrides?: CallOverrides): Promise<BigNumber>;

    VAMPIRE_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VOTE_WITH_FRIENDS(overrides?: CallOverrides): Promise<BigNumber>;

    VOTE_WITH_FRIENDS_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    arbitraryFinalizationAllowedAfter(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractRewards(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deploy(
      _initCode: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    enableTAHOETH(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    finalize(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    setBalancerPoolCandidate(
      balancerPoolCandidate: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    tahoEthDeployAllowed(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    APPROVAL_TARGET(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    APPROVAL_TARGET_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BALANCER_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BALANCER_POOL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BALANCER_POOL_CANDIDATE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CREATORS_NODE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CREATORS_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CREATORS_NODE_VETAHO(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CREATORS_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFI_NODE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFI_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFI_NODE_VETAHO(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFI_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    EDUCATE_NODE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    EDUCATE_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    EDUCATE_NODE_VETAHO(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    EDUCATE_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    EXPIRING_MERKLE_DISTRIBUTOR_FACTORY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GAME_PARAMETERS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    GAME_PARAMETERS_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GOVERNOR_BRAVO_V1_BASE_DELEGATE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    HUNTING_GROUND_REGISTRY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    HUNTING_GROUND_REGISTRY_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MERKLE_FACTORY_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SOCIAL_NODE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SOCIAL_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SOCIAL_NODE_VETAHO(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SOCIAL_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TAHOETH_HUNTING_GROUND_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TAHO_COMMUNITY_MULTISIG(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TAHO_DEPLOY_HASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TAHO_GOVERNOR_BRAVO_DELEGATE_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TAHO_GOVERNOR_BRAVO_DELEGATOR_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TAHO_SALT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TAHO_TOKEN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TIMELOCK(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TIMELOCK_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TREASURY_VESTER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TREASURY_VESTER_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAMPIRE_NODE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    VAMPIRE_NODE_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAMPIRE_NODE_VETAHO(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAMPIRE_NODE_VETAHO_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VOTE_WITH_FRIENDS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    VOTE_WITH_FRIENDS_DEPLOYER_DEPLOY_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    arbitraryFinalizationAllowedAfter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractRewards(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deploy(
      _initCode: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    enableTAHOETH(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    finalize(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setBalancerPoolCandidate(
      balancerPoolCandidate: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    tahoEthDeployAllowed(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
