/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGovernableApprovalTarget,
  IGovernableApprovalTargetInterface,
} from "../../../../contracts/test/MockTransferrer.sol/IGovernableApprovalTarget";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGovernableApprovalTarget__factory {
  static readonly abi = _abi;
  static createInterface(): IGovernableApprovalTargetInterface {
    return new utils.Interface(_abi) as IGovernableApprovalTargetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGovernableApprovalTarget {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IGovernableApprovalTarget;
  }
}
