/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TimelockGovernorWithEmergencyGovernance,
  TimelockGovernorWithEmergencyGovernanceInterface,
} from "../../../../contracts/governance/EmergencyGovernable.sol/TimelockGovernorWithEmergencyGovernance";

const _abi = [
  {
    inputs: [],
    name: "emergencyGovernance",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "timelock",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class TimelockGovernorWithEmergencyGovernance__factory {
  static readonly abi = _abi;
  static createInterface(): TimelockGovernorWithEmergencyGovernanceInterface {
    return new utils.Interface(
      _abi
    ) as TimelockGovernorWithEmergencyGovernanceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TimelockGovernorWithEmergencyGovernance {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TimelockGovernorWithEmergencyGovernance;
  }
}
