/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISubDeployer,
  ISubDeployerInterface,
} from "../../../../contracts/deployment/interfaces/ISubDeployer";

const _abi = [
  {
    inputs: [],
    name: "deploy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISubDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): ISubDeployerInterface {
    return new utils.Interface(_abi) as ISubDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISubDeployer {
    return new Contract(address, _abi, signerOrProvider) as ISubDeployer;
  }
}
