/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGovernableApprovalTarget } from "./IGovernableApprovalTarget";
export type { MockTransferrer } from "./MockTransferrer";
