/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iGoverableApprovalTargetSol from "./IGoverableApprovalTarget.sol";
export type { iGoverableApprovalTargetSol };
export type { IApprovalTarget } from "./IApprovalTarget";
export type { IEIP2612Token } from "./IEIP2612Token";
