/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAcceptTimelockAdmin,
  IAcceptTimelockAdminInterface,
} from "../../../contracts/TahoDeployer.sol/IAcceptTimelockAdmin";

const _abi = [
  {
    inputs: [],
    name: "acceptTimelockAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAcceptTimelockAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IAcceptTimelockAdminInterface {
    return new utils.Interface(_abi) as IAcceptTimelockAdminInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAcceptTimelockAdmin {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAcceptTimelockAdmin;
  }
}
