/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CreatorsNodeVeTaho } from "./CreatorsNodeVeTaho";
export type { DeFiNodeVeTaho } from "./DeFiNodeVeTaho";
export type { EducateNodeVeTaho } from "./EducateNodeVeTaho";
export type { SocialNodeVeTaho } from "./SocialNodeVeTaho";
export type { VampireNodeVeTaho } from "./VampireNodeVeTaho";
export type { VeTaho } from "./VeTaho";
