/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface ITahoDeployerInterface extends utils.Interface {
  functions: {
    "APPROVAL_TARGET()": FunctionFragment;
    "BALANCER_POOL()": FunctionFragment;
    "BALANCER_POOL_CANDIDATE()": FunctionFragment;
    "CREATORS_NODE_VETAHO()": FunctionFragment;
    "DEFI_NODE_VETAHO()": FunctionFragment;
    "EDUCATE_NODE_VETAHO()": FunctionFragment;
    "GAME_PARAMETERS()": FunctionFragment;
    "GOVERNOR_BRAVO_V1_BASE_DELEGATE()": FunctionFragment;
    "SOCIAL_NODE_VETAHO()": FunctionFragment;
    "TAHO_COMMUNITY_MULTISIG()": FunctionFragment;
    "TAHO_SALT()": FunctionFragment;
    "TAHO_TOKEN()": FunctionFragment;
    "TIMELOCK()": FunctionFragment;
    "VAMPIRE_NODE_VETAHO()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "APPROVAL_TARGET"
      | "BALANCER_POOL"
      | "BALANCER_POOL_CANDIDATE"
      | "CREATORS_NODE_VETAHO"
      | "DEFI_NODE_VETAHO"
      | "EDUCATE_NODE_VETAHO"
      | "GAME_PARAMETERS"
      | "GOVERNOR_BRAVO_V1_BASE_DELEGATE"
      | "SOCIAL_NODE_VETAHO"
      | "TAHO_COMMUNITY_MULTISIG"
      | "TAHO_SALT"
      | "TAHO_TOKEN"
      | "TIMELOCK"
      | "VAMPIRE_NODE_VETAHO"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "APPROVAL_TARGET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BALANCER_POOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BALANCER_POOL_CANDIDATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATORS_NODE_VETAHO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFI_NODE_VETAHO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EDUCATE_NODE_VETAHO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GAME_PARAMETERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNOR_BRAVO_V1_BASE_DELEGATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOCIAL_NODE_VETAHO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TAHO_COMMUNITY_MULTISIG",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TAHO_SALT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TAHO_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIMELOCK", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "VAMPIRE_NODE_VETAHO",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "APPROVAL_TARGET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BALANCER_POOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BALANCER_POOL_CANDIDATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CREATORS_NODE_VETAHO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFI_NODE_VETAHO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EDUCATE_NODE_VETAHO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GAME_PARAMETERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNOR_BRAVO_V1_BASE_DELEGATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOCIAL_NODE_VETAHO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TAHO_COMMUNITY_MULTISIG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TAHO_SALT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TAHO_TOKEN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TIMELOCK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VAMPIRE_NODE_VETAHO",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ITahoDeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITahoDeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    APPROVAL_TARGET(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    BALANCER_POOL(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    BALANCER_POOL_CANDIDATE(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    CREATORS_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    DEFI_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    EDUCATE_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    GAME_PARAMETERS(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    GOVERNOR_BRAVO_V1_BASE_DELEGATE(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    SOCIAL_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    TAHO_COMMUNITY_MULTISIG(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    TAHO_SALT(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    TAHO_TOKEN(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    TIMELOCK(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    VAMPIRE_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  APPROVAL_TARGET(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  BALANCER_POOL(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  BALANCER_POOL_CANDIDATE(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  CREATORS_NODE_VETAHO(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  DEFI_NODE_VETAHO(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  EDUCATE_NODE_VETAHO(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  GAME_PARAMETERS(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  GOVERNOR_BRAVO_V1_BASE_DELEGATE(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  SOCIAL_NODE_VETAHO(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  TAHO_COMMUNITY_MULTISIG(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  TAHO_SALT(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  TAHO_TOKEN(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  TIMELOCK(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  VAMPIRE_NODE_VETAHO(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    APPROVAL_TARGET(overrides?: CallOverrides): Promise<string>;

    BALANCER_POOL(overrides?: CallOverrides): Promise<string>;

    BALANCER_POOL_CANDIDATE(overrides?: CallOverrides): Promise<string>;

    CREATORS_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

    DEFI_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

    EDUCATE_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

    GAME_PARAMETERS(overrides?: CallOverrides): Promise<string>;

    GOVERNOR_BRAVO_V1_BASE_DELEGATE(overrides?: CallOverrides): Promise<string>;

    SOCIAL_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;

    TAHO_COMMUNITY_MULTISIG(overrides?: CallOverrides): Promise<string>;

    TAHO_SALT(overrides?: CallOverrides): Promise<string>;

    TAHO_TOKEN(overrides?: CallOverrides): Promise<string>;

    TIMELOCK(overrides?: CallOverrides): Promise<string>;

    VAMPIRE_NODE_VETAHO(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    APPROVAL_TARGET(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    BALANCER_POOL(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    BALANCER_POOL_CANDIDATE(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    CREATORS_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    DEFI_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    EDUCATE_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    GAME_PARAMETERS(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    GOVERNOR_BRAVO_V1_BASE_DELEGATE(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    SOCIAL_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    TAHO_COMMUNITY_MULTISIG(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    TAHO_SALT(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    TAHO_TOKEN(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    TIMELOCK(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    VAMPIRE_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    APPROVAL_TARGET(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    BALANCER_POOL(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    BALANCER_POOL_CANDIDATE(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    CREATORS_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    DEFI_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    EDUCATE_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    GAME_PARAMETERS(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    GOVERNOR_BRAVO_V1_BASE_DELEGATE(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    SOCIAL_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    TAHO_COMMUNITY_MULTISIG(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    TAHO_SALT(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    TAHO_TOKEN(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    TIMELOCK(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    VAMPIRE_NODE_VETAHO(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
