/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface FeePoolInterface extends utils.Interface {
  functions: {
    "accruedFees()": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "feeRate()": FunctionFragment;
    "feeRateLastUpdated()": FunctionFragment;
    "sharesPerDepositedUnderlying()": FunctionFragment;
    "targetManagementFee()": FunctionFragment;
    "totalSupply()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "accruedFees"
      | "balanceOf"
      | "feeRate"
      | "feeRateLastUpdated"
      | "sharesPerDepositedUnderlying"
      | "targetManagementFee"
      | "totalSupply"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accruedFees",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(functionFragment: "feeRate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeRateLastUpdated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sharesPerDepositedUnderlying",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetManagementFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "accruedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRateLastUpdated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharesPerDepositedUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetManagementFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;

  events: {};
}

export interface FeePool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FeePoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accruedFees(overrides?: CallOverrides): Promise<[BigNumber]>;

    balanceOf(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    feeRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    feeRateLastUpdated(overrides?: CallOverrides): Promise<[BigNumber]>;

    sharesPerDepositedUnderlying(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    targetManagementFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  accruedFees(overrides?: CallOverrides): Promise<BigNumber>;

  balanceOf(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  feeRate(overrides?: CallOverrides): Promise<BigNumber>;

  feeRateLastUpdated(overrides?: CallOverrides): Promise<BigNumber>;

  sharesPerDepositedUnderlying(overrides?: CallOverrides): Promise<BigNumber>;

  targetManagementFee(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    accruedFees(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    feeRate(overrides?: CallOverrides): Promise<BigNumber>;

    feeRateLastUpdated(overrides?: CallOverrides): Promise<BigNumber>;

    sharesPerDepositedUnderlying(overrides?: CallOverrides): Promise<BigNumber>;

    targetManagementFee(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    accruedFees(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    feeRate(overrides?: CallOverrides): Promise<BigNumber>;

    feeRateLastUpdated(overrides?: CallOverrides): Promise<BigNumber>;

    sharesPerDepositedUnderlying(overrides?: CallOverrides): Promise<BigNumber>;

    targetManagementFee(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    accruedFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOf(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    feeRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeRateLastUpdated(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sharesPerDepositedUnderlying(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    targetManagementFee(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
