/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBalancerBasePool,
  IBalancerBasePoolInterface,
} from "../../../../contracts/deployment/BalancerDeployer.sol/IBalancerBasePool";

const _abi = [
  {
    inputs: [],
    name: "getPoolId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBalancerBasePool__factory {
  static readonly abi = _abi;
  static createInterface(): IBalancerBasePoolInterface {
    return new utils.Interface(_abi) as IBalancerBasePoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBalancerBasePool {
    return new Contract(address, _abi, signerOrProvider) as IBalancerBasePool;
  }
}
