/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TokenWithCompoundStyleDelegation__factory } from "./TokenWithCompoundStyleDelegation__factory";
export { VoteWithFriends__factory } from "./VoteWithFriends__factory";
